### PR TITLE
[197] Manage Submissions Index

### LINKED ISSUE #197: Create Submissions & Evaluations list view: layout, basic Challenge Phase card
# What/Why
Implements the main index/landing page when the user visits `/manage_submissions`. The page shows a list of the challenge phases managed by the challenge manager.

### Figma Link
[Submissions & Evaluations - mobile](https://www.figma.com/design/VfdBFG8ShVnOStdSNYy9fR/Challenge.Gov-Component-Library?node-id=1477-72380&t=Kv7NiCIW7nfy2csU-1)

## Acceptance Criteria
- [x] Card list contains all the users challenge phases
- [x] Card has challenge phase title, challenge status, number of submissions, link to Eval Form (if exists) and evaluation end date
- [x] Card has two buttons: "Manage Evaluators", "View Submissions"
  - These two views are not built yet and the buttons can be no-op for now

_Disregard the following if this work **does not** include any UI changes_
- [x] WAVE screenshot
- [x] Automated a11y tests (axe-rspec specs)
- [x] Keyboard accessibility (tab navigation, form interactions)
- [x] Responsiveness at desktop and mobile

### PR DESCRIPTION
**Pull request by stonefilipczak**
Adds a list of the challenge manager's challenges to the /manage_submissions index view along with their associated submissions and evaluation forms. 

Screen Shot 2024-10-17 at 12 58 01 PM

Screen Shot 2024-10-17 at 12 58 28 PM

Screen Shot 2024-10-17 at 12 58 52 PM

### CODE REVIEW

**Review by stepchud — CHANGES_REQUESTED** [review]
This should be responsive on mobile
Screenshot 2024-10-21 at 2 07 21 PM

**Comment by stepchud** [comment]
oh weird, the responsive layout only has effect at 480px width, and I guess my browser won't shrink that far without using the browser dev tools settings

**Comment by stonefilipczak** [comment]
> oh weird, the responsive layout only has effect at 480px width, and I guess my browser won't shrink that far without using the browser dev tools settings

Yep that's how it is with this type of table component from USWDS, and there's nothing we can do about it, it's hard coded into their library.

**Review by stepchud — APPROVED** [review]
this works, we'll probably need to revisit the responsiveness at some point, but I'm good with merging this to keep moving forward

**Pull request merged**
